ci: remove CYPRESS_RECORD_KEY, CYPRESS_PROJECT_ID and GITHUB_TOKEN

diff --git a/.github/workflows/deploy-to-prod-from-default.yml b/.github/workflows/deploy-to-prod-from-default.yml
--- a/.github/workflows/deploy-to-prod-from-default.yml
+++ b/.github/workflows/deploy-to-prod-from-default.yml
@@ -52,20 +52,16 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: E2E test on prod
+      - name: Run Cypress E2E Tests
+        # We run the tests through the command, and not using cypress-io/github-action@v6, because this is the only way to hide the logs.
+
         # Learn more about '> /dev/null 2>&1': https://stackoverflow.com/a/42919998
         # In essence it merges output and error streams and doesn't show errors in the terminal to avoid leakage of secrets in the pipeline
         run: |
           npx cypress run \
           --e2e \
-          --browser electron \
-          --record \
-          --parallel \
-          --group "Electron e2e prod" > /dev/null 2>&1 || (echo "E2E PROD TESTS FAILED!" && exit 1)
+          --browser electron > /dev/null 2>&1 || (echo "E2E PROD TESTS FAILED!" && exit 1)    
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
           CYPRESS_BASE_URL: ${{ secrets.INNER_CIRCLE_PROD_BASE_URL }}
           API_ROOT_URL: ${{ secrets.INNER_CIRCLE_PROD_TIME_API_ROOT_URL }}
           AUTH_API_ROOT_URL: ${{ secrets.INNER_CIRCLE_PROD_AUTH_API_ROOT_URL }}
