test: disable deploy step and add cleanup step

diff --git a/.github/workflows/deploy-to-prod-from-default.yml b/.github/workflows/deploy-to-prod-from-default.yml
--- a/.github/workflows/deploy-to-prod-from-default.yml
+++ b/.github/workflows/deploy-to-prod-from-default.yml
@@ -14,23 +14,23 @@ jobs:
     # without this it cannot login to the registry
     secrets: inherit
  
-  deploy-to-prod:
-    name: Deploy service to k8s for prod environment  
-    needs: [push-to-registry]
-    runs-on: self-hosted
-    steps:
-      - name: Check out the repo
-        uses: actions/checkout@v4
+  # deploy-to-prod:
+  #   name: Deploy service to k8s for prod environment  
+  #   needs: [push-to-registry]
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Check out the repo
+  #       uses: actions/checkout@v4
 
-      - name: Deploy
-        # We use quotes because without them some vars can break down other vars
-        run: |
-            helmfile cache cleanup && helmfile apply --namespace "${{ secrets.INNER_CIRCLE_PROD_NAMESPACE }}" -f ci/helmfile.yaml \
-            --state-values-set image.tag="sha-${{ github.sha }}" \
-            --state-values-set ingress.hostname="${{ secrets.INNER_CIRCLE_PROD_HOSTNAME }}" \
-            --state-values-set extraConfigMapEnvVars.API_ROOT_URL="${{ secrets.INNER_CIRCLE_PROD_TIME_API_ROOT_URL }}" \
-            --state-values-set extraConfigMapEnvVars.AUTH_API_ROOT_URL="${{ secrets.INNER_CIRCLE_PROD_AUTH_API_ROOT_URL }}" > "/var/log/inner-circle/deploy/$(date +%F)-${{ github.event.repository.name }}-run-${{ github.run_id }}-job-${{ job.check_run_id }}.log" 2>&1
-            # on the last line where we redirect output we don't add a line break for convenience because it is easy to make it wrong having an extra space after \ symbol which leads to exposure of logs to the public pipeline logs instead of the needed private file on a runner
+  #     - name: Deploy
+  #       # We use quotes because without them some vars can break down other vars
+  #       run: |
+  #           helmfile cache cleanup && helmfile apply --namespace "${{ secrets.INNER_CIRCLE_PROD_NAMESPACE }}" -f ci/helmfile.yaml \
+  #           --state-values-set image.tag="sha-${{ github.sha }}" \
+  #           --state-values-set ingress.hostname="${{ secrets.INNER_CIRCLE_PROD_HOSTNAME }}" \
+  #           --state-values-set extraConfigMapEnvVars.API_ROOT_URL="${{ secrets.INNER_CIRCLE_PROD_TIME_API_ROOT_URL }}" \
+  #           --state-values-set extraConfigMapEnvVars.AUTH_API_ROOT_URL="${{ secrets.INNER_CIRCLE_PROD_AUTH_API_ROOT_URL }}" > "/var/log/inner-circle/deploy/$(date +%F)-${{ github.event.repository.name }}-run-${{ github.run_id }}-job-${{ job.check_run_id }}.log" 2>&1
+  #           # on the last line where we redirect output we don't add a line break for convenience because it is easy to make it wrong having an extra space after \ symbol which leads to exposure of logs to the public pipeline logs instead of the needed private file on a runner
 
   e2e-test-prod:
     runs-on: self-hosted
@@ -38,7 +38,7 @@ jobs:
       image: cypress/browsers:node-22.18.0-chrome-138.0.7204.183-1-ff-141.0-edge-138.0.3351.121-1
       volumes: 
         - /var/log/inner-circle:/var/log/inner-circle
-    needs: [deploy-to-prod]
+    # needs: [deploy-to-prod]
     steps:
       - name: Check out the repo
         uses: actions/checkout@v4
@@ -61,3 +61,10 @@ jobs:
           AUTH_API_ROOT_URL: ${{ secrets.INNER_CIRCLE_PROD_AUTH_API_ROOT_URL }}
           USER_LOGIN: ${{ secrets.INNER_CIRCLE_PROD_AUTH_FIRST_TENANT_LOGIN_WITH_ALL_PERMISSIONS  }}
           USER_PASSWORD: ${{ secrets.INNER_CIRCLE_PROD_AUTH_FIRST_TENANT_PASSWORD_WITH_ALL_PERMISSIONS  }}
+
+      - name: Cleanup
+        if: always()
+        run: |
+          # This cleanup step is needed to delete all files (including hidden files) from the working directory 
+          # so that the repo can be successfully checked out in the future pipelines
+          sudo rm -rf ./* ./.[!.]* || true
