test

diff --git a/.github/workflows/deploy-to-prod-from-default.yml b/.github/workflows/deploy-to-prod-from-default.yml
--- a/.github/workflows/deploy-to-prod-from-default.yml
+++ b/.github/workflows/deploy-to-prod-from-default.yml
@@ -3,48 +3,48 @@ name: Deploy to Prod and e2e test to prod
 on:
   push:
     branches:
-      - master
+      - feature/*
 
 jobs:
-  # this is needed to wait for the new docker image to be build and published to the registry
-  # so that we can use the image to run ui of the needed commit related version as part of local-env
-  # the idea is taken from here https://stackoverflow.com/a/71489231
-  push-to-registry:
-    uses: ./.github/workflows/.reusable-docker-build-and-push.yml
-    # without this it cannot login to the registry
-    secrets: inherit
+  # # this is needed to wait for the new docker image to be build and published to the registry
+  # # so that we can use the image to run ui of the needed commit related version as part of local-env
+  # # the idea is taken from here https://stackoverflow.com/a/71489231
+  # push-to-registry:
+  #   uses: ./.github/workflows/.reusable-docker-build-and-push.yml
+  #   # without this it cannot login to the registry
+  #   secrets: inherit
 
-  deploy-to-prod:
-    name: Deploy service to k8s for prod environment  
-    needs: [push-to-registry]
-    runs-on: ubuntu-24.04
-    steps:
-      - name: Check out the repo
-        uses: actions/checkout@v4
+  # deploy-to-prod:
+  #   name: Deploy service to k8s for prod environment  
+  #   needs: [push-to-registry]
+  #   runs-on: ubuntu-24.04
+  #   steps:
+  #     - name: Check out the repo
+  #       uses: actions/checkout@v4
 
-      - name: Create default global .kube/config file
-        run: |
-          cd $HOME
-          mkdir .kube
-          echo "${{ secrets.INNER_CIRCLE_PROD_KUBECONFIG }}" > .kube/config
+  #     - name: Create default global .kube/config file
+  #       run: |
+  #         cd $HOME
+  #         mkdir .kube
+  #         echo "${{ secrets.INNER_CIRCLE_PROD_KUBECONFIG }}" > .kube/config
 
-      - name: Deploy
-        uses: helmfile/helmfile-action@v1.9.0
-        with:
-          helmfile-version: 'v0.164.0'
-          helm-version: 'v3.18.0'
-          helmfile-args: >
-            apply --suppress-diff --namespace ${{ secrets.INNER_CIRCLE_PROD_NAMESPACE }} -f ci/helmfile.yaml 
-            --state-values-set image.tag=sha-${{ github.sha }} 
-            --state-values-set ingress.hostname=${{ secrets.INNER_CIRCLE_PROD_HOSTNAME }}
-            --state-values-set extraConfigMapEnvVars.API_ROOT_URL=${{ secrets.INNER_CIRCLE_PROD_TIME_API_ROOT_URL }}
-            --state-values-set extraConfigMapEnvVars.AUTH_API_ROOT_URL=${{ secrets.INNER_CIRCLE_PROD_AUTH_API_ROOT_URL }}
-          helmfile-auto-init: "false"
+  #     - name: Deploy
+  #       uses: helmfile/helmfile-action@v1.9.0
+  #       with:
+  #         helmfile-version: 'v0.164.0'
+  #         helm-version: 'v3.18.0'
+  #         helmfile-args: >
+  #           apply --suppress-diff --namespace ${{ secrets.INNER_CIRCLE_PROD_NAMESPACE }} -f ci/helmfile.yaml 
+  #           --state-values-set image.tag=sha-${{ github.sha }} 
+  #           --state-values-set ingress.hostname=${{ secrets.INNER_CIRCLE_PROD_HOSTNAME }}
+  #           --state-values-set extraConfigMapEnvVars.API_ROOT_URL=${{ secrets.INNER_CIRCLE_PROD_TIME_API_ROOT_URL }}
+  #           --state-values-set extraConfigMapEnvVars.AUTH_API_ROOT_URL=${{ secrets.INNER_CIRCLE_PROD_AUTH_API_ROOT_URL }}
+  #         helmfile-auto-init: "false"
 
   e2e-test-prod:
     runs-on: ubuntu-24.04
     container: cypress/browsers:node-22.18.0-chrome-138.0.7204.183-1-ff-141.0-edge-138.0.3351.121-1
-    needs: [deploy-to-prod]
+    # needs: [deploy-to-prod]
     steps:
       - name: Check out the repo
         uses: actions/checkout@v4
@@ -52,20 +52,15 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: E2E test on prod
-        # Learn more about '> /dev/null 2>&1': https://stackoverflow.com/a/42919998
-        # In essence it merges output and error streams and doesn't show errors in the terminal to avoid leakage of secrets in the pipeline
-        run: |
-          npx cypress run \
-          --e2e \
-          --browser electron \
-          --record \
-          --parallel \
-          --group "Electron e2e prod" > /dev/null 2>&1 || (echo "E2E PROD TESTS FAILED!" && exit 1)
+      - name: Run Cypress E2E Tests
+        uses: cypress-io/github-action@v6
+        with:
+          browser: electron
+          # Learn more about '> /dev/null 2>&1': https://stackoverflow.com/a/42919998
+          # In essence it merges output and error streams and doesn't show errors in the terminal to avoid leakage of secrets in the pipeline
+          command: |
+            npx cypress run --e2e --browser electron > /dev/null 2>&1 || (echo "E2E PROD TESTS FAILED!" && exit 1)     
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
           CYPRESS_BASE_URL: ${{ secrets.INNER_CIRCLE_PROD_BASE_URL }}
           API_ROOT_URL: ${{ secrets.INNER_CIRCLE_PROD_TIME_API_ROOT_URL }}
           AUTH_API_ROOT_URL: ${{ secrets.INNER_CIRCLE_PROD_AUTH_API_ROOT_URL }}
